### ISSUE TITLE
PayPal secret keys

### ISSUE THREAD

**Issue by ltfschoen** [takuyaokamoto11/payment_app#1]
Can I use your secret keys? https://github.com/takuyaokamoto11/payment_app/commit/a9540316d6695b83e7a99a444ef537cba7bf8dbb#diff-40f1765cacc4f7768c749c242de9f2f4R8

**Comment by takuyaokamoto11** [comment]
Thank you, Luke! but ok! this key is provided by PayPal SDK as an example! so not my key! :)
